# Generated by Django 5.2.6 on 2025-11-19 04:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('nombre_usuario', models.CharField(max_length=255)),
                ('telefono_celular', models.CharField(max_length=20, unique=True)),
                ('bio', models.TextField(blank=True, max_length=255, null=True)),
                ('pais', models.TextField(blank=True, max_length=20, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('otp_codigo', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_creado_en', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='Para evitar conflictos con el modelo de Django', related_name='usuarios', related_query_name='usuario', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Para evitar conflictos con el modelo de Django', related_name='usuarios', related_query_name='usuario', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
