# Generated by Django 5.2.7 on 2025-11-02 21:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('Temp_Media', models.FloatField()),
                ('Humedad_Media', models.FloatField()),
                ('Longitud_Tallo', models.FloatField()),
                ('Diametro_Tallo', models.FloatField()),
                ('Peso_Racimo_Medio', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
