# Generated by Django 5.2.7 on 2025-11-05 01:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PrediccionTomate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField(db_index=True)),
                ("dia_predicho", models.DateField()),
                ("produccion_predicha_kg", models.FloatField()),
                ("dias_usados", models.JSONField()),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Predicción de tomate",
                "verbose_name_plural": "Predicciones de tomate",
                "ordering": ["-creado_en"],
            },
        ),
    ]
